name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python mkdocs-autorefs
          pip install -e .  # Install your package if needed for docs

      # Step 4: Build and Deploy Documentation
      - name: Build and Deploy Documentation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # Create the .nojekyll file to disable Jekyll processing
          touch site/.nojekyll
          mkdocs gh-deploy --force
